[build]
  publish = "src"





[[redirects]]
  from = "/resume"
  to = "/cruz_resume.html"
  status = 200

[[redirects]]
  from = "/cover-letter"
  to = "/cruz_coverLetter.html"
  status = 200

[[redirects]]
  from = "/landing"
  to = "/landing.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200



# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404



# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com https://*.cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com https://*.cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self'"

# Cache control with cache-busting strategy
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    ETag = "true"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    ETag = "true"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"
    ETag = "true"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"
    ETag = "true"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"
    ETag = "true"

[[headers]]
  for = "*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"
    ETag = "true"

# Gzip compression is enabled by default on Netlify 